services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    environment:
      PORT: '${PORT}'
      JWT_SECRET: '${JWT_SECRET}'
      STRIPE_SECRET_KEY: '${STRIPE_SECRET_KEY}'
      EMAIL_HOST: '${EMAIL_HOST}'
      EMAIL_PORT: '${EMAIL_PORT}'
      EMAIL_HOST_USER: '${EMAIL_HOST_USER}'
      EMAIL_HOST_PASSWORD: '${EMAIL_HOST_PASSWORD}'
      EMAIL_FROM: '${EMAIL_FROM}'
      DATABASE_URL: '${DATABASE_URL}'
      REDIS_URL: '${REDIS_URL}'
      NODE_ENV: '${NODE_ENV}'

    volumes:
      - .:/usr/src/app # Mounts the local directory to the container
      - /usr/src/app/node_modules # Prevents overwriting of node_modules by the mount

    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: giftcart
    ports:
      - '5433:5432'
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'

volumes:
  postgres_data:
